package org.clyze.source.irfitter.source.model;

import org.clyze.persistent.model.Position;
import org.clyze.source.irfitter.base.AccessType;

/**
 * An access to an outer class instance (C.this). This class is about the
 * information recorded during source parsing. Source-IR matching will then
 * resolve these accesses and replace them by appropriate metadata (such as
 * accesses to "this$0" fields).
 */
public class OuterThis {
    /** The source position where this access is found. */
    public final SourceFile srcFile;
    /** The source position of this access. */
    public final Position pos;
    /** The target type of the access. */
    public final JType outerClass;

    public OuterThis(SourceFile srcFile, Position pos, JType outerClass) {
        this.srcFile = srcFile;
        this.pos = pos;
        this.outerClass = outerClass;
    }

    /**
     * Returns a field access to "this$0".
     * @param fieldId      the field generated by javac
     * @return             the source code field access
     */
    public JFieldAccess getFieldAccess(String fieldId) {
        return new JFieldAccess(srcFile, pos, AccessType.READ, fieldId, null);
    }

    @Override
    public String toString() {
        return "OuterThis: " + outerClass + Utils.getLocation(srcFile.getRelativePath(), pos);
    }
}
